### ISSUE TITLE
Gradle@2 Task Fails with Exit Code 128 on uploadMappingRelease in Azure Pipelines

### ISSUE THREAD

**Issue by smarkars** [DataDog/dd-sdk-android-gradle-plugin#346]
We are using the `Gradle@2` task in an Azure DevOps pipeline to build our app and upload the ProGuard mapping file. However, the pipeline run fails with the following error during the `uploadMappingRelease` step:  

```
[org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command 'git'' finished with non-zero exit value 128
```

The same Gradle command runs successfully in a local development environment, but fails in the CI/CD pipeline.  

#### **Pipeline Configuration**  
```yaml
- task: Gradle@2
  inputs:
    tasks: 'clean localization test bundleRelease assembleRelease uploadMappingRelease'
```

build.gradle

```gradle
datadog {
    site                   = "EU1"
    remoteRepositoryUrl    = "https://<remoteurl>"
    checkProjectDependencies = "none"
}
```

Is there a way to disable any Git-related information collection when running uploadMappingRelease?

Would appreciate any insights on how to resolve this issue!
